### ISSUE TITLE
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with: Error: ENOENT: no such file or directory, stat '/Users/jeremy/Desktop/throwAway/another/tmp/source_map_concat-input_base_path-Pym6qjwe.tmp/0/bower_components/BaremetricsCalendar/public/js/Calendar.js'

### ISSUE THREAD

**Issue by notmessenger** [davewasmer/ember-baremetrics-calendar#1]
**Steps to reproduce**
1. `ember new testApp`
2. `ember install ember-baremetrics-calendar`
3. `ember serve`

**Error Received**

```
ember serve
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.

Just getting started with Ember? Please visit http://localhost:4200/ember-getting-started to get going

Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat '/Users/jeremy/Desktop/throwAway/another/tmp/source_map_concat-input_base_path-Pym6qjwe.tmp/0/bower_components/BaremetricsCalendar/public/js/Calendar.js'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at ConcatWithMaps.keyForFile (/Users/jeremy/Desktop/throwAway/another/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/Users/jeremy/Desktop/throwAway/another/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:112:65)
    at /Users/jeremy/Desktop/throwAway/another/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/jeremy/Desktop/throwAway/another/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/jeremy/Desktop/throwAway/another/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/jeremy/Desktop/throwAway/another/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/jeremy/Desktop/throwAway/another/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

The broccoli plugin was instantiated at:
    at ConcatWithMaps.Plugin (/Users/jeremy/Desktop/throwAway/another/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at ConcatWithMaps.CachingWriter [as constructor] (/Users/jeremy/Desktop/throwAway/another/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:21:10)
    at new ConcatWithMaps (/Users/jeremy/Desktop/throwAway/another/node_modules/ember-cli/node_modules/broccoli-concat/concat.js:22:17)
    at module.exports (/Users/jeremy/Desktop/throwAway/another/node_modules/ember-cli/node_modules/broccoli-concat/index.js:26:10)
    at EmberApp.concatFiles (/Users/jeremy/Desktop/throwAway/another/node_modules/ember-cli/lib/broccoli/ember-app.js:348:10)
    at EmberApp.javascript (/Users/jeremy/Desktop/throwAway/another/node_modules/ember-cli/lib/broccoli/ember-app.js:1214:12)
    at EmberApp.toArray (/Users/jeremy/Desktop/throwAway/another/node_modules/ember-cli/lib/broccoli/ember-app.js:1566:10)
    at EmberApp.toTree (/Users/jeremy/Desktop/throwAway/another/node_modules/ember-cli/lib/broccoli/ember-app.js:1588:30)
    at module.exports (/Users/jeremy/Desktop/throwAway/another/ember-cli-build.js:23:14)
    at CoreObject.module.exports.Task.extend.setupBroccoliBuilder (/Users/jeremy/Desktop/throwAway/another/node_modules/ember-cli/lib/models/builder.js:54:19)
```

**Workaround**
1. `bower install BaremetricsCalendar`

**Comment by davewasmer** [comment]
Should be fixed in 0.0.3
